apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainticket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainticket-app
  template:
    metadata:
      labels:
        app: trainticket-app
    spec:
      containers:
        - name: trainticket
          image: 436312201622.dkr.ecr.ap-south-1.amazonaws.com/trainticket-ecr:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: trainticket-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: trainticket-app
